### ISSUE TITLE
An error after Dyn Prompt update

### ISSUE THREAD

**Issue by miasik** [klimaleksus/stable-diffusion-webui-embedding-merge#16]
I've reported the issue there
https://github.com/adieyal/sd-dynamic-prompts/issues/761
Can you help?

**Comment by aleksusklim** [comment]
Updated WebUI on latest dev, EM on latest sdxl, and Dyn on latest main.
For me works fine at default settings of Dyn.

There is a Settings page `Uncategorized → Dynamic Prompts` where you can set `{` and `}` characters. Are you sure they are not `<` and `>` for you, by chance?

**Comment by miasik** [comment]
Checked it again right now and it works fine. I'm sure that I haven't updated anything or changed in settings. Magic!
Thanks! ;-)

**Comment by aleksusklim** [comment]
![Mr Snail employee of the month](https://github.com/klimaleksus/stable-diffusion-webui-embedding-merge/assets/13969463/ba298bec-2368-4423-9f0b-874ceb042d12)
