### ISSUE TITLE
Not An Issue - An INSPRIATION!

### ISSUE THREAD

**Issue by duskfallcrew** [klimaleksus/stable-diffusion-webui-embedding-merge#20]
AHem <_< i'm always going to be an A111 user and i have YET TO test this, and I didn't know how to properly fork without it. being the SAME exact thing. 

I suc kat coding, i'm already paying fro claude so i figured i'd tackle the whole move to comfyUI thing: https://github.com/duskfallcrew/Comfyui_EmbeddingMerge_Node

I SO do not want to claim it as my own, i know this is just ONE part and i dont understand comfyUI enough, but i figured i'd show it off and see how it went? :D

**Comment by aleksusklim** [comment]
Wait, how did you ported the whole thing which I made as opaque as a hell?
Hmm, it's only around 150 lines in code. Is that really enough?..

I haven't tested it yet, but I doubt that your math parser is correct in edge cases, and also that your general pattern matcher works as is should (for example, I thinks yours would fail to include a literal ' in a string anyhow; also if the expression was opened with `{'` it should be closed only with `}` and not `>`)

I'll see what can be improved there!

**Comment by aleksusklim** [comment]
Is your node even working in the first place?

The repo does not have `__init__.py` file, but this is solved by renaming `merge_embed.py` into it.

Then, the node takes `model` pipe instead of `clip` pipe. How that should work? I believe the CLIP pipe is crucial.
Also, there is no sense to save the embedding right here; instead, there should be node that saves a final `conditioning`.

Moreover, I doubt how would you "load" an embedding here at runtime for it to be used inside expressions?
Additional node might print the table with tensor values, taking the `conditioning`.

**Comment by ash-bluepollution95** [comment]
I don't tend to load embeddings anyways, i actually litereally just merge words to tokens when i do it, meaning i don't usually know how to merge my embeeddings even with your instructions? :D

**Comment by ash-bluepollution95** [comment]
> Wait, how did you ported the whole thing which I made as opaque as a hell? Hmm, it's only around 150 lines in code. Is that really enough?..
> 
> I haven't tested it yet, but I doubt that your math parser is correct in edge cases, and also that your general pattern matcher works as is should (for example, I thinks yours would fail to include a literal ' in a string anyhow; also if the expression was opened with `{'` it should be closed only with `}` and not `>`)
> 
> I'll see what can be improved there!

Me and math = failure, i'll ask around more I figured porting it to comfyui was not a bing bang boom LOL

**Comment by ash-bluepollution95** [comment]
Also feel free to actually poke at the repo itself, i'm not great at coding i'mma admit i acutally get AI help to do it because i can't even type fast enough before my ADHD gets to me.

**Comment by aleksusklim** [comment]
Is your code WORKING (meaning, you can add the repo into comfy custom nodes and then actually load your node to merge embedding and see the result), or this is merely a DRAFT of a future custom node?

**Comment by ash-bluepollution95** [comment]
I haven't tested to see what's up yet, i dont understand comfyui enough yet - i'm still parsing through projects that i had ideas for - so i'm going to assume partial draft - i have to get someone that's a normal comfyui user to test it, and if it doesn't work thats fine.. i mean i'm still trying to work on my HF backup A1111 plugin lol.

**Comment by ash-bluepollution95** [comment]
Am taking stabs at making sure it's more solid xD i think it's more "DRAFT" now than anything else until i fully understand what i'm doing

**Comment by ash-bluepollution95** [comment]
I don't know if it's going to work even after gemini went nuts at it, lmao - i've been told in ehtory "YOU CAN DO THIS WITHOUT" a node in comfyui, but comfyUI and it's "VISUAL NODE PROGRAMMER" nonsense ... yea just no, i think i'm going to give up and let someone else play with this, i really can't see me moving to ComfyUI any time soon after trying like 5 times to ask an AI how to make it work, i don't trust the current version i did either, i'mma close the comment XD you can go peek at teh new changes but it's like "HEY I CUT 90% OF THE CODE" and just doesn't feel like it'll work.
